### ISSUE TITLE
how can i set the size of emoji

### ISSUE THREAD

**Issue by janetwu** [rodrigopolo/minEmoji#17]

**Comment by bxyoung89** [comment]
They replace the character with a span like this 
`<span class="em" style="background:url(PATH_TO_MIN_EMOJI);"></span>`.

Just style the span using the .em class in CSS.

**Comment by janetwu** [comment]
can style using background-size,but it cannot support some older browsers,thx anyway

**Comment by rodrigopolo** [comment]
Sorry for the delay, I have tons of work.

I got the Apple emojis from the original Apple Font on OS X (macOS), I use a Ruby script to extract the PNG images from the font, then I join all the images creating a SVG file and converting the file to a PNG with all the images as one... that is the first part, second part is creating the CSS styles, the ones that define the width and height of the emoji, using the same logic I created a node.js script for creating that CSS style sheet, it has some vars that can be changed in order to display other size than 20x20px

Here is the last version I created:
https://github.com/rodrigopolo/minEmoji/tree/master/sprite_gen3
