### ISSUE TITLE
support for middlefinger ;-)

### ISSUE THREAD

**Issue by celevra** [rodrigopolo/minEmoji#8]
Hi,

can you implement the middlefinger?
http://emojipedia.org/reversed-hand-with-middle-finger-extended/

regards

celevra

**Comment by rodrigopolo** [comment]
I'll implement all of the latest unicode 8.0 and iOS 9.2 emojis, I'm only waiting for the next OS X release which I hope include all the latest emoji/pngs, if not I'll use Emoji One instead of twemoji or iOS, here is the current state of the work on all projects:
http://rodrigopolo.com/files/emojilist/

**Comment by rodrigopolo** [comment]
The "iOS8" version (which is now really iOS 9.1) has been updated with the latest emojis, check it out:
http://rodrigopolo.github.io/minEmoji/minEmoji_iOS8/demo.html
